# Generated by Django 3.2 on 2021-04-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('price', models.CharField(max_length=10, verbose_name='Ціна')),
                ('characteristics', models.TextField(verbose_name='Характеристики')),
                ('date', models.DateField(verbose_name='Дата'))
            ],
            options={
                'verbose_name': 'Асортиметн/Каталог',
                'verbose_name_plural': 'Асортиметн/Каталог',
            },
        ),
    ]
