# Generated by Django 3.2 on 2021-05-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.TextField(null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Діагональ екрану')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплею')),
                ('reslution', models.CharField(max_length=255, verbose_name='Розширення екрану')),
                ('accum_volume', models.CharField(max_length=200, verbose_name="Об'єм акумулятора")),
                ('ram', models.CharField(max_length=255, verbose_name="Оперативна пам'ять")),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name="Максимальний об'єм SD-карти")),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Основна камера')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Фронтальна камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.TextField(null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('core', models.CharField(max_length=2, verbose_name='Кількість ядер')),
                ('threads', models.CharField(max_length=3, verbose_name='Кількість потоків')),
                ('cesh', models.CharField(max_length=2, verbose_name='Кеш')),
                ('power', models.CharField(max_length=3, verbose_name='ТДП')),
                ('core_freq', models.CharField(max_length=5, verbose_name='Частота процессора')),
                ('boost', models.BooleanField(default=True, verbose_name='Turbo Boost(+/-)')),
                ('video', models.BooleanField(default=True, verbose_name='Встроєне графічне ядро(+/-)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
